[package]
name = "courier-main-wrapper"
version = "0.2.0"
edition = "2021"
publish = false
description = "A dedicated main wrapper for courier server software"
license = "MIT"

[dependencies]
libc = "0.2.158"